/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sharkylabs_comm_JNICanReader */

#ifndef _Included_com_sharkylabs_comm_JNICanReader
#define _Included_com_sharkylabs_comm_JNICanReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sharkylabs_comm_JNICanReader
 * Method:    poll
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_sharkylabs_comm_JNICanReader_poll
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
